version: '3.8'

services:
  pgsql:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: manumafe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_repo
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - pgsql:/data/postgres

volumes:
  pgsql:
